This program takes the input of a file and print the names of all the columns. The user can select the column number and that particular column will then be annonymized and the program will then return two csv files one containing the key and value and other the annonimized file.

In [1]:
import numpy as np
import pandas as pd
import string    
import random

In [2]:
from google.colab import files
uploaded = files.upload()

Saving Engagement_FY_E (Responses) - Form Responses 1 - Sheet10.csv to Engagement_FY_E (Responses) - Form Responses 1 - Sheet10.csv

In [6]:
#Enter the name of the file
file_name=input("Enter the file name with .csv extension")

Enter the file name with .csv extensionEngagement_FY_E (Responses) - Form Responses 1 - Sheet10.csv

In [7]:
import io
df2 = pd.read_csv(io.BytesIO(uploaded[file_name]))

In [8]:
df2

,User_id,Were the activities you did on PyGuru interesting?,Did you enjoyed the programming concepts learnt on PyGuru?,Did you wish you had been doing something else rather than learning programming on PyGuru?,Describe your mood during learning programming on PyGuru?,How well were you concentrating while learning the programming concepts in PyGuru?,Describe your mood while programming on PyGuru in terms of activeness?,How well were you focussed while learning the programming concepts on PyGuru?,Affective Engagement,Cognitive Engagement,Post_Test
0,451,4,5,4,1,5,5,1,14,11,2
1,480,4,4,5,2,5,4,3,15,12,3
2,494,5,5,5,1,5,5,1,16,11,2
3,464,4,4,4,3,4,4,2,15,10,2
4,501,2,3,3,3,3,4,2,11,9,5
5,451,5,5,1,1,4,5,6,12,15,2
6,453,3,3,4,5,4,3,4,15,11,7
7,447,4,4,3,5,4,5,6,16,15,2
8,461,3,4,1,5,3,4,6,13,13,2
9,497,5,5,5,4,4,5,5,19,14,4
10,485,5,5,1,1,5,5,1,12,11,4
11,464,4,3,3,2,3,4,2,12,9,2
12,494,5,5,2,6,5,5,7,18,17,2
13,488,5,5,1,2,5,4,2,13,11,2
14,500,4,5,2,1,5,4,1,12,10,4
15,461,5,5,1,1,4,5,2,12,11,2
16,468,4,3,1,2,3,4,3,10,10,6
17,488,5,4,1,6,4,3,6,16,13,2
18,501,4,5,4,3,4,4,3,16,11,5
19,480,5,5,3,2,4,5,2,15,11,3
20,453,5,5,4,1,5,5,2,15,12,7
21,484,5,4,3,5,4,3,6,17,13,6
22,457,3,3,2,3,3,3,5,11,11,4
23,453,5,5,1,3,4,5,2,14,11,7
24,484,5,5,5,2,5,4,1,17,10,6
25,485,3,4,3,6,4,3,4,16,11,4
26,504,5,5,2,3,4,3,2,15,9,3
27,452,5,5,5,2,5,5,2,17,12,5
28,488,4,4,1,6,5,4,6,15,15,2
29,480,5,5,1,1,5,5,1,12,11,3
30,494,3,5,4,1,4,4,2,13,10,2
31,485,5,4,5,2,5,5,3,16,13,4
32,480,4,4,5,2,4,4,2,15,10,3
33,494,3,4,1,2,4,3,3,10,10,2
34,468,5,5,2,2,4,4,6,14,14,6
35,500,4,4,2,2,4,4,5,12,13,4
36,461,4,5,3,6,4,4,4,18,12,2

In [9]:
col_name=list((df2.columns))

In [10]:
dict_col_name={}
for i in range(1,len(list(df2.columns))+1):
  dict_col_name[i]=col_name[i-1]

In [11]:
dict_col_name

{1: 'User_id',
 2: 'Were the activities you did on PyGuru interesting?',
 3: 'Did you enjoyed the programming concepts learnt  on PyGuru?',
 4: 'Did you wish you had been doing something else rather than learning programming on PyGuru?',
 5: 'Describe your mood during learning programming on PyGuru?',
 6: 'How well were you concentrating while learning the programming concepts in PyGuru?',
 7: 'Describe your mood while programming on PyGuru in terms of activeness?',
 8: 'How well were you focussed while learning the programming concepts on PyGuru?',
 9: 'Affective Engagement',
 10: 'Cognitive Engagement',
 11: 'Post_Test'}

In [12]:
#enter the column numbers to be annonimized seperated by commas without space
col_num=input("enter the column numbers to be annonimized seperated by commas without space")

enter the column numbers to be annonimized seperated by commas without space1,2,4

In [13]:
col_name_list= [int(i) for i in col_num.split(",") if i.isdigit()]

In [14]:
col_name_list

[1, 2, 4]

In [15]:
dict_col_name[col_name_list[0]]

'User_id'

In [25]:
S = 5  # number of characters in the string.

key_value=pd.DataFrame({})
for j in col_name_list:
  dict_key={}
  for i in df2[dict_col_name[j]]:
    ran = ''.join(random.choices(string.ascii_uppercase + string.digits, k = S))
    dict_key[ran]= i
  key_value[dict_col_name[j]]=list(df2[dict_col_name[j]])
  key_value[dict_col_name[j]+str("_key")]=list(dict_key.keys())
  df2[dict_col_name[j]]=list(dict_key.keys())

In [23]:
key_value.to_csv("key_value.csv")

In [26]:
df2

,User_id,Were the activities you did on PyGuru interesting?,Did you enjoyed the programming concepts learnt on PyGuru?,Did you wish you had been doing something else rather than learning programming on PyGuru?,Describe your mood during learning programming on PyGuru?,How well were you concentrating while learning the programming concepts in PyGuru?,Describe your mood while programming on PyGuru in terms of activeness?,How well were you focussed while learning the programming concepts on PyGuru?,Affective Engagement,Cognitive Engagement,Post_Test
0,TMEK0,ZL9SQ,5,B30RK,1,5,5,1,14,11,2
1,X087E,T77WR,4,FN2BZ,2,5,4,3,15,12,3
2,VR943,BY5VT,5,O9F6Y,1,5,5,1,16,11,2
3,VWOXO,I2K5R,4,J9Q1G,3,4,4,2,15,10,2
4,0HKX3,T2E7X,3,4LM0X,3,3,4,2,11,9,5
5,SG4RF,1WUC4,5,EAEYD,1,4,5,6,12,15,2
6,L8KRI,YGDTK,3,EADK3,5,4,3,4,15,11,7
7,J4H6C,QZHWQ,4,VZJZ0,5,4,5,6,16,15,2
8,0LDZH,CAXT0,4,9XAV2,5,3,4,6,13,13,2
9,CCWZJ,ITQ9J,5,MAP4R,4,4,5,5,19,14,4
10,338GD,MTB6G,5,B55DJ,1,5,5,1,12,11,4
11,BXKIG,KKBSZ,3,6S2AO,2,3,4,2,12,9,2
12,NHERF,6PS27,5,5FG4R,6,5,5,7,18,17,2
13,6UCN9,M5XXR,5,GL0BZ,2,5,4,2,13,11,2
14,2OU7S,FW724,5,3VOKM,1,5,4,1,12,10,4
15,Y35TF,24EBI,5,F47HE,1,4,5,2,12,11,2
16,BJ219,0BXA1,3,X704P,2,3,4,3,10,10,6
17,BWK56,M4SW5,4,02HXU,6,4,3,6,16,13,2
18,Q4VGE,B00AA,5,9JT05,3,4,4,3,16,11,5
19,A0X1M,2FBH5,5,VZCSP,2,4,5,2,15,11,3
20,I1NCJ,7N9AW,5,3BK0Q,1,5,5,2,15,12,7
21,C9XGP,GXIOF,4,NKNNG,5,4,3,6,17,13,6
22,HIVHF,NG1Y5,3,XYRES,3,3,3,5,11,11,4
23,61BK0,UVKTH,5,WMI1U,3,4,5,2,14,11,7
24,YLC9V,SCDWU,5,UDOQD,2,5,4,1,17,10,6
25,ZZTVP,ITBJE,4,RCFHG,6,4,3,4,16,11,4
26,UUJ8S,GM69N,5,GB1GU,3,4,3,2,15,9,3
27,KQMIE,K1YK6,5,C2UX8,2,5,5,2,17,12,5
28,0D2XG,HT60K,4,DG59O,6,5,4,6,15,15,2
29,7SBD8,KM77C,5,U9NEV,1,5,5,1,12,11,3
30,BNHWL,G10SC,5,63TLS,1,4,4,2,13,10,2
31,XG4QM,KECV5,4,9LCXE,2,5,5,3,16,13,4
32,1YV3F,E5MKD,4,FL8EI,2,4,4,2,15,10,3
33,WXP3I,ADE1I,4,0GJ2L,2,4,3,3,10,10,2
34,3PWNJ,GCKR9,5,2NSS7,2,4,4,6,14,14,6
35,ZWX7J,KVNED,4,XJXZ7,2,4,4,5,12,13,4
36,REH5Z,83BJG,5,DGJRW,6,4,4,4,18,12,2

In [27]:
df2.to_csv("annonimized_file.csv")